name: Build static ffmpeg

on:
  push:
  pull_request:

jobs:
  package-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - i686
          - armhf
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get install nasm
      - name: Install i686 cross-compile dependencies
        run: sudo apt-get install gcc-multilib
        if: matrix.arch == 'i686'
      - name: Install armhf cross-compile dependencies
        run: sudo apt-get install gcc-multilib-arm-linux-gnueabihf
        if: matrix.arch == 'armhf'
      - name: Build
        run: |
          mkdir artifacts
          ./build-linux.sh
          mv ffmpeg-*-audio-linux-* artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ffmpeg-linux-${{ env.ARCH }}
          path: artifacts/

  package-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - i686
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get install nasm mingw-w64
      - name: Build
        run: |
          mkdir artifacts
          ./build-windows.sh
          mv ffmpeg-*-audio-windows-* artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ffmpeg-windows-${{ env.ARCH }}
          path: artifacts/

  package-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch:
          - x86_64
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: brew install nasm
      - name: Build
        run: |
          mkdir artifacts
          ./build-macos.sh
          mv ffmpeg-*-audio-macos-** artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ffmpeg-macos-${{ env.ARCH }}
          path: artifacts/

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - package-linux
      - package-windows
      - package-macos
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: ffmpeg-linux-x86_64
          path: artifacts/
      - uses: actions/download-artifact@v1
        with:
          name: ffmpeg-linux-i686
          path: artifacts/
      - uses: actions/download-artifact@v1
        with:
          name: ffmpeg-linux-armhf
          path: artifacts/
      - uses: actions/download-artifact@v1
        with:
          name: ffmpeg-windows-x86_64
          path: artifacts/
      - uses: actions/download-artifact@v1
        with:
          name: ffmpeg-windows-i686
          path: artifacts/
      - uses: actions/download-artifact@v1
        with:
          name: ffmpeg-macos-x86_64
          path: artifacts/
      - name: Make tarballs
        run: |
          mkdir artifacts/release/
          cd artifacts/
          dirs=$(find . -name 'ffmpeg-*' -type d)
          for dir in $dirs
          do
            name=$(basename $dir)
            tar cvzf release/$name.tar.gz $dir
          done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
